### ISSUE TITLE
rails 4.x : Fix the strong params

### ISSUE THREAD

**Issue by shadowbq** [shadowbq/cartoque#1]
http://guides.rubyonrails.org/action_controller_overview.html#strong-parameters

**Comment by shadowbq** [comment]
``` ruby
1) UpgradesController PUT update gets back_url right on post-its
      Failure/Error: model.update_attributes(*args)

      ActiveModel::ForbiddenAttributesError:
        ActiveModel::ForbiddenAttributesError

 # /usr/local/rvm/gems/ruby-2.2.3/gems/activemodel-4.1.14/lib/active_model/forbidden_attributes_protection.rb:21:in `sanitize_for_mass_assignment'
      # /usr/local/rvm/gems/ruby-2.2.3/gems/mongoid-4.0.2/lib/mongoid/attributes/processing.rb:22:in `process_attributes'
      # /usr/local/rvm/gems/ruby-2.2.3/gems/mongoid-4.0.2/lib/mongoid/attributes.rb:205:in `block in assign_attributes'
      # /usr/local/rvm/gems/ruby-2.2.3/gems/mongoid-4.0.2/lib/mongoid/threaded/lifecycle.rb:26:in `_assigning'
      # /usr/local/rvm/gems/ruby-2.2.3/gems/mongoid-4.0.2/lib/mongoid/attributes.rb:204:in `assign_attributes'
      # /usr/local/rvm/gems/ruby-2.2.3/gems/mongoid-4.0.2/lib/mongoid/persistable/updatable.rb:51:in `update'
      # ./app/decorators/resource_decorator.rb:48:in `update_attributes'
```
