### ISSUE TITLE
Mongoid alize failing tests 

### ISSUE THREAD

**Issue by shadowbq** [shadowbq/cartoque#3]
https://github.com/dzello/mongoid_alize

**Comment by shadowbq** [comment]
```
  152) Server mongoid_denormalized updates #operating_system_name correctly
       Failure/Error: sys = OperatingSystem.create!(name: "Linux")

      NoMethodError:
         undefined method `ancestry_depth' for #<OperatingSystem:0x00000007beb458>
       # /usr/local/rvm/gems/ruby-2.2.3/gems/mongoid-4.0.2/lib/mongoid/validatable.rb:79:in `read_attribute_for_validation'

```

**Comment by shadowbq** [comment]
```
  151) Server mongoid_denormalized updates #physical_rack_full_name correctly
       Failure/Error: physical_rack_fields.try(:fetch, 'full_name') if physical_rack_id.present?

       NameError:
         undefined local variable or method `physical_rack_fields' for #<Server:0x00000009afd030>
       # ./app/models/server.rb:247:in `physical_rack_full_name'
       # ./spec/models/server_spec.rb:268:in `block (3 levels) in <top (required)>'
```
