### ISSUE TITLE
RAILS4.x: RSPEC3 possible bad syntax (Test::Unit DSL in Spec test?)

### ISSUE THREAD

**Issue by shadowbq** [shadowbq/cartoque#8]
```
  35) ServersController real ServersController gets index
      Failure/Error: assert_not_nil assigns(:servers)

      NoMethodError:
        undefined method `assert_not_nil' for #<RSpec::ExampleGroups::ServersController::RealServersController:0x000000072a3a08>
      # /usr/local/rvm/gems/ruby-2.2.3/gems/actionpack-4.1.14/lib/action_dispatch/testing/assertions/routing.rb:171:in `method_missing'
      # ./spec/controllers/servers_controller_spec.rb:32:in `block (3 levels) in <top (required)>'
```

**Comment by shadowbq** [comment]
https://github.com/shadowbq/cartoque/blob/rails4.x/spec/controllers/servers_controller_spec.rb

``` ruby
  it "gets index" do
      get :index
      assert_response :success
      assert_not_nil assigns(:servers)
    end
```
